
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 12 20:54:17 CST 2019
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int parizquierdo = 6;
  public static final int menorque = 30;
  public static final int menos = 3;
  public static final int rstring = 16;
  public static final int rread = 80;
  public static final int puntoycoma = 9;
  public static final int rtoInt = 68;
  public static final int rstatic = 64;
  public static final int punto = 71;
  public static final int corderecho = 58;
  public static final int menorigualque = 32;
  public static final int rfor = 46;
  public static final int rint = 12;
  public static final int mas = 2;
  public static final int cadena = 24;
  public static final int dospuntos = 51;
  public static final int rprotected = 61;
  public static final int rdouble = 13;
  public static final int rinstanceof = 79;
  public static final int umenos = 81;
  public static final int interrogacion = 52;
  public static final int rprintln = 27;
  public static final int rtoDouble = 67;
  public static final int parderecho = 7;
  public static final int or = 36;
  public static final int mayorque = 31;
  public static final int caracter = 25;
  public static final int id = 26;
  public static final int rextends = 70;
  public static final int rtrue = 22;
  public static final int rboolean = 15;
  public static final int corizquierdo = 57;
  public static final int rchar = 14;
  public static final int menosmenos = 54;
  public static final int rread_file = 77;
  public static final int rnew = 59;
  public static final int rfalse = 23;
  public static final int rfinal = 65;
  public static final int rvoid = 19;
  public static final int llaveder = 11;
  public static final int relse = 41;
  public static final int and = 37;
  public static final int rabstract = 63;
  public static final int rgraph = 75;
  public static final int mayorigualque = 33;
  public static final int rdefault = 50;
  public static final int rdo = 47;
  public static final int xor = 38;
  public static final int rnull = 73;
  public static final int division = 5;
  public static final int rthis = 72;
  public static final int EOF = 0;
  public static final int rclass = 17;
  public static final int rsuper = 76;
  public static final int rswitch = 48;
  public static final int rpublic = 60;
  public static final int rreturn = 56;
  public static final int diferenteque = 35;
  public static final int rprinttabla = 29;
  public static final int rwhile = 42;
  public static final int error = 1;
  public static final int entero = 20;
  public static final int rwrite_file = 78;
  public static final int rpow = 55;
  public static final int rbreak = 43;
  public static final int rimport = 74;
  public static final int igualigual = 34;
  public static final int rif = 40;
  public static final int rcase = 49;
  public static final int por = 4;
  public static final int rprivate = 62;
  public static final int rprint = 28;
  public static final int coma = 18;
  public static final int modulo = 45;
  public static final int not = 39;
  public static final int doble = 21;
  public static final int igual = 8;
  public static final int rcontinue = 44;
  public static final int rstr = 66;
  public static final int masmas = 53;
  public static final int llaveizq = 10;
  public static final int rtoChar = 69;
}

